package action

const (
	EMPTY = "empty"

	// Menu
	MENU_TODO           = "menu-todo"
	MENU_CHALLANGES     = "menu-challanges"
	MENU_RECOMMENDATION = "menu-recommendation"
	MENU_SETTINGS       = "menu-settings"

	// Todo
	TODO_ADD     = "todo-add"
	TODO_TODOS   = "todo-todos"
	TODO_HISTORY = "todo-history"

	// Challenges
	CHALLENGE_ADD        = "challenge-add"
	CHALLENGE_CHALLENGES = "challenge-challenges"
	CHALLENGE_HISTORY    = "challenge-history"

	// Todo New
	TODO_NEW_NOTIFICATION = "todo-new-notificaton"
	TODO_NEW_TIME         = "todo-new-time"
	TODO_NEW_DEADLINE     = "todo-new-deadline"
	TODO_NEW_TITLE        = "todo-new-title"
	TODO_NEW_DESCRIPTION  = "todo-new-description"
	TODO_NEW_PICTURE      = "todo-new-picture"
	TODO_NEW_FILE         = "todo-new-file"
	TODO_NEW_SAVE         = "todo-new-save"
	TODO_NEW_CANCEL       = "todo-new-cancel"

	// Clock
	CLOCK_1  = "clock!1"
	CLOCK_2  = "clock!2"
	CLOCK_3  = "clock!3"
	CLOCK_4  = "clock!4"
	CLOCK_5  = "clock!5"
	CLOCK_6  = "clock!6"
	CLOCK_7  = "clock!7"
	CLOCK_8  = "clock!8"
	CLOCK_9  = "clock!9"
	CLOCK_10 = "clock!10"
	CLOCK_11 = "clock!11"
	CLOCK_12 = "clock!12"
	CLOCK_13 = "clock!13"
	CLOCK_14 = "clock!14"
	CLOCK_15 = "clock!15"
	CLOCK_16 = "clock!16"
	CLOCK_17 = "clock!17"
	CLOCK_18 = "clock!18"
	CLOCK_19 = "clock!19"
	CLOCK_20 = "clock!20"
	CLOCK_21 = "clock!21"
	CLOCK_22 = "clock!22"
	CLOCK_23 = "clock!23"
	CLOCK_24 = "clock!24"

	// Day
	DAY_1  = "day!1"
	DAY_2  = "day!2"
	DAY_3  = "day!3"
	DAY_4  = "day!4"
	DAY_5  = "day!5"
	DAY_6  = "day!6"
	DAY_7  = "day!7"
	DAY_8  = "day!8"
	DAY_9  = "day!9"
	DAY_10 = "day!10"
	DAY_11 = "day!11"
	DAY_12 = "day!12"
	DAY_13 = "day!13"
	DAY_14 = "day!14"
	DAY_15 = "day!15"
	DAY_16 = "day!16"
	DAY_17 = "day!17"
	DAY_18 = "day!18"
	DAY_19 = "day!19"
	DAY_20 = "day!20"
	DAY_21 = "day!21"
	DAY_22 = "day!22"
	DAY_23 = "day!23"
	DAY_24 = "day!24"
	DAY_25 = "day!25"
	DAY_26 = "day!26"
	DAY_27 = "day!27"
	DAY_28 = "day!28"
	DAY_29 = "day!29"
	DAY_30 = "day!30"
	DAY_31 = "day!31"

	// Month
	MONTH_1  = "month!1"
	MONTH_2  = "month!2"
	MONTH_3  = "month!3"
	MONTH_4  = "month!4"
	MONTH_5  = "month!5"
	MONTH_6  = "month!6"
	MONTH_7  = "month!7"
	MONTH_8  = "month!8"
	MONTH_9  = "month!9"
	MONTH_10 = "month!10"
	MONTH_11 = "month!11"
	MONTH_12 = "month!12"
)
